server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: payment-service
              uri: http://payment-service:8082
              predicates:
                - Path=/api/payment/**

            - id: payment-service-direct
              uri: http://payment-service:8082
              predicates:
                - Path=/payment/**

            - id: settlement-service
              uri: http://settlement-service:8084
              predicates:
                - Path=/api/settlement/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG